version: '3'

services:
  wpapp:
    build: .
    image: hoanvv/php7.4-fpm
    container_name: wpapp
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: wpapp
      SERVICE_TAGS: wpdev
    working_dir: /var/www
    volumes: 
      - ./:/var/www
      - ./docker-config/php/local.ini:/usr/local/lib/local.ini
    networks: 
      - wpapp-network

  wpserver:
    image: nginx:alpine
    container_name: wpserver
    restart: unless-stopped
    tty: true
    ports:
      - "90:80"
      - "449:443"
    volumes:
      - ./:/var/www
      - ./docker-config/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - wpapp-network

  wpdb:
    image: mysql:5.7.31
    container_name: wpdb
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: rocketcomics
      MYSQL_ROOT_PASSWORD: rocket1231
      SERVICE_TAGS: wpdev
      SERVICE_NAME: mysql
    volumes: 
      - dbdata:/var/lib/mysql
      - ./docker-config/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker-config/mysql/db:/docker-entrypoint-initdb.d
    networks: 
      - wpapp-network
#Volumes
volumes:
  dbdata:
    driver: local

#Docker Networks
networks:
  wpapp-network:
    driver: bridge